### PR TITLE
Symbolic utils extension

### PR DESCRIPTION
**Pull request by jverzani**
This PR adds an extension for `SymbolicUtils`. With this loaded, the rewriting rules of `SymbolicUtils` can be used, which should expand the feature set of `SymEngine.jl`.

```
julia> using SymEngine, SymbolicUtils
@
julia> @vars x y
(x, y)

julia> simplify(sin(x)^2 + cos(x)^2)
1
```

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good. Can you add some tests?

**Comment by jverzani** [comment]
Ok, borrowed examples from https://symbolicutils.juliasymbolics.org/rewrite/#rule-based_rewriting to do so.

**Comment by isuruf** [comment]
Restarting fixed it.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
