### PR TITLE
Julia v0.7 support

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by jverzani** [comment]
There are some other things to clean up that femto cleaner didn't, but these are minor. Can you find why this now fails (i'm striking out):

```
using SymEngine
@vars x
x + pi
```

whereas this does not?

```
@vars x
x + pi
```

There is some thing going on with promotion and Irrationals that has changed.

**Comment by isuruf** [comment]
@jverzani, I don't get it. For the 2nd script to work, don't you need `using SymEngine` at the beginning?

**Comment by jverzani** [comment]
Sorry, yes. But when you do add that, you get an error from the conversion
of `pi` when it goes through the promotion mechanism. There were changes to
how the math constants fit into Julia, and I think that is the underlying
cause, but I couldn't track it down. Here is the start of the infinite loop:

```

julia> x + pi

┌ Warning: Constructors no longer fall back to `convert`. A constructor
`Basic(::Int64)` should be defined instead.

│   caller = zero at mathops.jl:32 [inlined]

└ @ Core mathops.jl:32

┌ Warning: Constructors no longer fall back to `convert`. A constructor
`Basic(::Int64)` should be defined instead.

│   caller = zero(::Type{SymEngine.BasicType{Val{:Integer}}}) at
mathops.jl:37

└ @ SymEngine mathops.jl:37

^CERROR: InterruptException:

Stacktrace:

 [1] backtrace() at ./stacktraces.jl:189

 [2] macro expansion at ./deprecated.jl:75 [inlined]

 [3] macro expansion at ./logging.jl:304 [inlined]

 [4] depwarn(::String, ::Symbol) at ./deprecated.jl:71

 [5] finalizer(::Basic, ::Function) at ./deprecated.jl:56

 [6] Type at /Users/verzani/julia/SymEngine/src/types.jl:19 [inlined]

 [7] convert(::Type{Basic}, ::Int64) at
/Users/verzani/julia/SymEngine/src/types.jl:31

 [8] Basic(::Int64) at ./deprecated.jl:472

 [9] zero(::Type{SymEngine.BasicType{Val{:Integer}}}) at
/Users/verzani/julia/SymEngine/src/mathops.jl:37

 [10] real(::Type) at ./complex.jl:108

 [11] promote_rule(::Type{Irrational{:π}},
::Type{SymEngine.BasicType{Val{:Integer}}}) at ./irrationals.jl:26

 [12] promote_type(::Type{Irrational{:π}},
::Type{SymEngine.BasicType{Val{:Integer}}}) at ./promotion.jl:221

 [13] promote_rule(::Type{Irrational{:π}},
::Type{SymEngine.BasicType{Val{:Integer}}}) at ./irrationals.jl:26

 [14] promote_type(::Type{Irrational{:π}},
::Type{SymEngine.BasicType{Val{:Integer}}}) at ./promotion.jl:221
```

**Comment by isuruf** [comment]
Fixed in d611d8a.

**Comment by jverzani** [comment]
Great job. Thanks for the efforts here!

**Pull request merged**
