### PR TITLE
GitHub actions

### LINKED ISSUE #222: Move to GitHub actions?
When looking at the build info of #221, I recognized the message

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

It might be good to move to GitHub actions.

### PR DESCRIPTION
**Pull request by ranocha**
I enabled CI via GitHub actions and removed Travis CI. It would be nice if someone could enable Codecov and Coveralls for this repository (since I don't have the permissions there).

Closes #222

### CODE REVIEW

**Comment by ranocha** [comment]
Bump

**Comment by ranocha** [comment]
Is there any interest in this?

**Comment by isuruf** [comment]
Looks good to me. Thanks for the PR

**Comment by isuruf** [comment]
I think I enabled coveralss and codecov.

**Pull request merged**
