### PR TITLE
added basic_neq

### PR DESCRIPTION
**Pull request by kunal-iitkgp**
@isuruf pls review

### CODE REVIEW

**Comment by isuruf** [comment]
There is already a test for `!=` which means just `==` is enough

**Comment by kunal-iitkgp** [comment]
but isn't this the default Base Operator?

**Comment by isuruf** [comment]
What I meant is that, you don't need to explicitly define `!=` because it is implicitly defined when `==` is defined

**Comment by kunal-iitkgp** [comment]
okay! I got it now

**Pull request closed without merging**
