### PR TITLE
Use Binaries instead of Conda in windows

### PR DESCRIPTION
**Pull request by isuruf**
@Datseris, @ChrisRackauckas, @musm, what do you think about this?
This would remove the dependency on Conda for windows.
I installed symengine through conda, removed unnecessary things and archived the folder. Now it's downloading a 5MB archive for windows.

### CODE REVIEW

**Comment by isuruf** [comment]
@ChrisRackauckas, can you review?

**Comment by ChrisRackauckas** [comment]
LGTM

**Comment by isuruf** [comment]
Thansk

**Comment by Datseris** [comment]
Wait , wait " # SymEngine can only be installed to a python 3.5 environment " ? I only have Python 2.7 ! 
I just learned that SymEngine requires Python 3.5. Could this be the reason for all the errors I am getting??

**Comment by Datseris** [comment]
Also, how can I test if this PR works? My package update did not update sym engine

**Comment by isuruf** [comment]
Nope. Conda.jl would have  created a Python 3.5 environment.
With this PR, I've removed Conda on Windows. Can you check that this works?
```Julia
Pkg.checkout("SymEngine")
Pkg.build("SymEngine")
```

**Comment by Datseris** [comment]
Everything is ok! , sorry pasting long code now for safety reasons!:
```
julia> Pkg.checkout("SymEngine")
INFO: Checking out SymEngine master...
INFO: Pulling SymEngine latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("SymEngine")
INFO: Building Conda
INFO: Building SymEngine
WARNING: Base.WORD_SIZE is deprecated.
  likely near C:\Users\migos\.julia\v0.5\SymEngine\deps\build.jl:11
INFO: Attempting to Create directory C:\Users\migos\.julia\v0.5\SymEngine\deps\downloads
INFO: Downloading file https://github.com/symengine/symengine/releases/download/v0.2.0/binaries-msvc-x86_64.tar.bz2
INFO: Done downloading file https://github.com/symengine/symengine/releases/download/v0.2.0/binaries-msvc-x86_64.tar.bz2
INFO: Attempting to Create directory C:\Users\migos\.julia\v0.5\SymEngine
INFO: Directory C:\Users\migos\.julia\v0.5\SymEngine already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\migos\.julia\v0.5\SymEngine\deps\downloads\binaries-msvc-x86_64.tar.bz2

Extracting  binaries-msvc-x86_64.tar
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive:

Extracting  usr\include\symengine\polys\uintpoly.h
Extracting  usr\bin\api-ms-win-crt-time-l1-1-0.dll
Extracting  usr\include\gmp-impl.h
Extracting  usr\include\symengine\eval_mpfr.h
Extracting  usr\include\symengine\polys\uintpoly_flint.h
Extracting  usr\include\symengine\basic-methods.inc
Extracting  usr\bin\api-ms-win-crt-utility-l1-1-0.dll
Extracting  usr\include\symengine\polys\uexprpoly.h
Extracting  usr\lib\gmp.lib
Extracting  usr\include\symengine\symengine_exception.h
Extracting  usr\include\symengine\printer.h
Extracting  usr\bin\api-ms-win-core-namedpipe-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-conio-l1-1-0.dll
Extracting  usr\bin\api-ms-win-core-processthreads-l1-1-0.dll
Extracting  usr\bin\api-ms-win-core-util-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-string-l1-1-0.dll
Extracting  usr\include\symengine\visitor.h
Extracting  usr\licenses\mpir
Extracting  usr\bin\concrt140.dll
Extracting  usr\bin\api-ms-win-core-file-l1-2-0.dll
Extracting  usr\licenses\symengine
Extracting  usr\include\symengine\polys\msymenginepoly.h
Extracting  usr\bin\api-ms-win-core-console-l1-1-0.dll
Extracting  usr\include\symengine\fields.h
Extracting  usr\lib
Extracting  usr\include\mpirxx.h
Extracting  usr\include\symengine\matrix.h
Extracting  usr\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
Extracting  usr\bin\symengine.dll
Extracting  usr\bin\vcomp140.dll
Extracting  usr\lib\gmp_static.lib
Extracting  usr\include\symengine\mp_wrapper.h
Extracting  usr\include\symengine\ntheory.h
Extracting  usr\include\symengine\monomials.h
Extracting  usr\include\symengine\derivative.h
Extracting  usr\include\symengine\series.h
Extracting  usr\bin\api-ms-win-crt-private-l1-1-0.dll
Extracting  usr\bin\api-ms-win-core-synch-l1-1-0.dll
Extracting  usr\lib\mpir.lib
Extracting  usr\include\symengine\series_visitor.h
Extracting  usr\bin\api-ms-win-core-errorhandling-l1-1-0.dll
Extracting  usr\include\symengine\rings.h
Extracting  usr\bin\api-ms-win-core-libraryloader-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-stdio-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-filesystem-l1-1-0.dll
Extracting  usr\include\symengine\lambda_double.h
Extracting  usr\bin\api-ms-win-core-memory-l1-1-0.dll
Extracting  usr\include\symengine\complex_mpc.h
Extracting  usr\include\symengine\eval.h
Extracting  usr\include\gmp-longlong.h
Extracting  usr\bin\api-ms-win-core-processthreads-l1-1-1.dll
Extracting  usr\lib\gmpxx_static.lib
Extracting  usr\include
Extracting  usr\include\symengine\series_generic.h
Extracting  usr\include\symengine\sets.h
Extracting  usr\include\symengine\dict.h
Extracting  usr\include\symengine\cwrapper.h
Extracting  usr\include\symengine\real_double.h
Extracting  usr\bin\api-ms-win-crt-convert-l1-1-0.dll
Extracting  usr\bin\api-ms-win-core-interlocked-l1-1-0.dll
Extracting  usr\include\symengine\infinity.h
Extracting  usr\CMake\SymEngineConfig.cmake
Extracting  usr\include\symengine\eval_mpc.h
Extracting  usr\include\symengine\polys\basic_conversions.h
Extracting  usr\include\symengine\symengine_rcp.h
Extracting  usr\include\symengine\polys\uratpoly.h
Extracting  usr\bin\api-ms-win-core-file-l2-1-0.dll
Extracting  usr\bin\api-ms-win-core-string-l1-1-0.dll
Extracting  usr\include\symengine\diophantine.h
Extracting  usr\include\symengine\eval_double.h
Extracting  usr\include\symengine\polys\uintpoly_piranha.h
Extracting  usr\include\gmpxx.h
Extracting  usr\bin\gmp.dll
Extracting  usr\bin
Extracting  usr\bin\ucrtbase.dll
Extracting  usr\include\symengine\polys
Extracting  usr\include\symengine\complex.h
Extracting  usr\include\symengine\polys\usymenginepoly.h
Extracting  usr\include\symengine\symbol.h
Extracting  usr\include\symengine\polys\upolybase.h
Extracting  usr\bin\api-ms-win-core-synch-l1-2-0.dll
Extracting  usr\include\symengine\symengine_assert.h
Extracting  usr
Extracting  usr\bin\api-ms-win-crt-process-l1-1-0.dll
Extracting  usr\bin\api-ms-win-core-profile-l1-1-0.dll
Extracting  usr\include\symengine\basic.h
Extracting  usr\bin\api-ms-win-core-processenvironment-l1-1-0.dll
Extracting  usr\include\symengine\basic-inl.h
Extracting  usr\include\symengine\mp_class.h
Extracting  usr\bin\api-ms-win-crt-math-l1-1-0.dll
Extracting  usr\include\symengine\series_piranha.h
Extracting  usr\licenses\mpir\COPYING.LIB
Extracting  usr\licenses\mpir\COPYING
Extracting  usr\include\symengine\codegen.h
Extracting  usr\bin\api-ms-win-core-handle-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-heap-l1-1-0.dll
Extracting  usr\include\symengine
Extracting  usr\include\symengine\pow.h
Extracting  usr\CMake\SymEngineTargets.cmake
Extracting  usr\include\symengine\mul.h
Extracting  usr\bin\api-ms-win-core-debug-l1-1-0.dll
Extracting  usr\include\symengine\integer.h
Extracting  usr\include\symengine\logic.h
Extracting  usr\include\gmp.h
Extracting  usr\include\symengine\add.h
Extracting  usr\include\symengine\finitediff.h
Extracting  usr\bin\vccorlib140.dll
Extracting  usr\bin\msvcp140.dll
Extracting  usr\include\symengine\rational.h
Extracting  usr\include\symengine\symengine_export.h
Extracting  usr\include\symengine\functions.h
Extracting  usr\bin\api-ms-win-core-heap-l1-1-0.dll
Extracting  usr\bin\mpir_static.pdb
Extracting  usr\lib\mpirxx_static.lib
Extracting  usr\bin\api-ms-win-core-datetime-l1-1-0.dll
Extracting  usr\bin\api-ms-win-crt-locale-l1-1-0.dll
Extracting  usr\include\symengine\eval_arb.h
Extracting  usr\include\symengine\number.h
Extracting  usr\CMake\SymEngineTargets-release.cmake
Extracting  usr\include\mpir.h
Extracting  usr\include\symengine\complex_double.h
Extracting  usr\bin\api-ms-win-core-sysinfo-l1-1-0.dll
Extracting  usr\include\symengine\real_mpfr.h
Extracting  usr\bin\api-ms-win-crt-runtime-l1-1-0.dll
Extracting  usr\include\symengine\expression.h
Extracting  usr\include\symengine\series_flint.h
Extracting  usr\CMake
Extracting  usr\bin\api-ms-win-core-file-l1-1-0.dll
Extracting  usr\include\symengine\symengine_config.h
Extracting  usr\bin\api-ms-win-crt-multibyte-l1-1-0.dll
Extracting  usr\licenses\symengine\LICENSE
Extracting  usr\licenses
Extracting  usr\lib\mpir_static.lib
Extracting  usr\lib\symengine.lib
Extracting  usr\include\gmp-config.h
Extracting  usr\bin\vcruntime140.dll
Extracting  usr\bin\api-ms-win-crt-environment-l1-1-0.dll
Extracting  usr\bin\mpir.dll
Extracting  usr\bin\api-ms-win-core-timezone-l1-1-0.dll
Extracting  usr\bin\mpir.pdb
Extracting  usr\include\symengine\constants.h
Extracting  usr\include\symengine\subs.h
Extracting  usr\include\symengine\type_codes.inc
Extracting  usr\bin\api-ms-win-core-localization-l1-2-0.dll
Extracting  usr\bin\mpirxx_static.pdb


Extracting  Everything is Okusr\CMake\SymEngineConfigVersion.cmake

Size:       0
Compressed: 5608215

Extracting  usr\include\symengine\parser.h
Extracting  usr\include\symengine\flint_wrapper.h
Extracting  usr\include\gmp-mparam.h

Everything is Ok

Folders: 10
Files: 139
Size:       26660437
Compressed: 77312
```

**Comment by isuruf** [comment]
That's great. Can you also check that
```Julia
Pkg.test("SymEngine")
``` 
works?

**Comment by Datseris** [comment]
```
julia> Pkg.test("SymEngine")
INFO: Testing SymEngine
(1/2)*x - 5*x*y + x^2
1/2 + 2*x - 5*y
INFO: SymEngine tests passed
```

**Comment by certik** [comment]
What are the problems with using Conda on Windows? Just so that I know for other projects. I was hoping that Conda can be the standard go-to solution for providing binaries on all platforms. So I am interested to see why it's not a good solution here.

**Comment by isuruf** [comment]
Saw another user getting #56 on gitter. Also I think we should move for a MinGW build of symengine for Julia.

**Comment by isuruf** [comment]
Also, there have been failures in installing conda for no reason. This is okay for a user when installing, but not when we are automatically downloading miniconda and using it.

**Pull request merged**
