### PR TITLE
Use conda envs

### PR DESCRIPTION
**Pull request by isuruf**
@ChrisRackauckas, can you check that this works with Conda.jl master?

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
On SymEngine master:

```julia
julia> Pkg.checkout("Conda")
INFO: Checking out Conda master...
INFO: Pulling Conda latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("Conda")
INFO: Building Conda

julia> Pkg.build("SymEngine")
INFO: Building Conda
INFO: Building SymEngine
Warning: 'conda-forge' already in 'channels' list, moving to the top
Warning: 'symengine' already in 'channels' list, moving to the top
Fetching package metadata .............
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - enum34 -> python 2.6*|2.7*|3.3*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.


==============================[ ERROR: SymEngine ]==============================

LoadError: failed process: Process(setenv(`'C:\Users\Chris\.julia\v0.5\Conda\deps\usr\Scripts\conda.exe' install -y python=3.5`,String["USERDOMAIN_ROAMINGPROFILE=CHRISRACKBED","HOMEPATH=\\Users\\Chris","ProgramData=C:\\ProgramData","ProgramW6432=C:\\Program Files","PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","SESSIONNAME=Console","APPDATA=C:\\Users\\Chris\\AppData\\Roaming","PUBLIC=C:\\Users\\Public","USERDOMAIN=CHRISRACKBED","OS=Windows_NT","PROCESSOR_REVISION=3c03","TMP=C:\\Users\\Chris\\AppData\\Local\\Temp","NVTOOLSEXT_PATH=C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\","ALLUSERSPROFILE=C:\\ProgramData","Path=C:\\Users\\Chris\\AppData\\Local\\Julia-0.5.0\\bin;C:\\Users\\Chris\\AppData\\Local\\Julia-0.5.0\\bin;C:\\Program Files\\ImageMagick-6.9.5-Q16;C:\\Program Files\\ImageMagick-7.0.2-Q16;C:\\Program Files\\ImageMagick-7.0.1-Q16;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\libnvvp;C:\\Program Files (x86)\\Razer Chroma SDK\\bin;C:\\Program Files\\Razer Chroma SDK\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\;C:\\Program Files\\MATLAB\\R2015b\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\Chris\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\CMake\\bin;C:\\Users\\Chris\\AppData\\Local\\Julia-0.4.5;C:\\Program Files\\MATLAB\\R2015b\\bin\\win64;C:\\Program Files\\cURL\\bin;C:\\Program Files (x86)\\LyX 2.2\\Perl\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\HashiCorp\\Vagrant\\bin;c:\\users\\chris\\appdata\\local\\enthought\\canopy\\user\\scripts;C:\\Users\\Chris\\AppData\\Local\\Enthought\\Canopy\\User;C:\\Program Files\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin;C:\\Users\\Chris\\AppData\\Local\\atom\\bin","COMPUTERNAME=CHRISRACKBED","FP_NO_HOST_CHECK=NO","USERNAME=Chris","CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files","CommonProgramFiles=C:\\Program Files\\Common Files","CUDA_PATH=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5","USERPROFILE=C:\\Users\\Chris","CONDARC=C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr\\condarc-julia.yml","PSModulePath=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\","PROCESSOR_LEVEL=6","=C:=C:\\Users\\Chris\\.julia\\v0.5\\SymEngine\\deps","SystemDrive=C:","TEMP=C:\\Users\\Chris\\AppData\\Local\\Temp","HOMEDRIVE=C:","LOCALAPPDATA=C:\\Users\\Chris\\AppData\\Local","VS120COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\","PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel","NUMBER_OF_PROCESSORS=8","asl.log=Destination=file","ComSpec=C:\\WINDOWS\\system32\\cmd.exe","VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\","SystemRoot=C:\\WINDOWS","CUDA_PATH_V7_5=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5","CONDA_DEFAULT_ENV=C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr","ProgramFiles(x86)=C:\\Program Files (x86)","NVCUDASAMPLES7_5_ROOT=C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v7.5","VS110COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\","LOGONSERVER=\\\\CHRISRACKBED","CONDA_PREFIX=C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr","windir=C:\\WINDOWS","FPS_BROWSER_USER_PROFILE_STRING=Default","MATLAB_HOME=C:\\Program Files\\MATLAB\\R2015b","CommonProgramW6432=C:\\Program Files\\Common Files","ProgramFiles=C:\\Program Files","FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer","NVCUDASAMPLES_ROOT=C:\\ProgramData\\NVIDIA Corporation\\CUDA Samples\\v7.5","PROCESSOR_ARCHITECTURE=AMD64","OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading C:\Users\Chris\.julia\v0.5\SymEngine\deps\build.jl, in expression starting on line 12

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: SymEngine had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("SymEngine")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by ChrisRackauckas** [comment]
Oh wait, this wasn't merged.

**Comment by ChrisRackauckas** [comment]
Stalls waiting for input:

```julia
julia> Pkg.build("SymEngine")
INFO: Building Conda
INFO: Building SymEngine
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Chris\.julia\v0.6\SymEngine\deps\usr:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zlib-1.2.8                 |                0         116 KB

The following NEW packages will be INSTALLED:

    zlib: 1.2.8-0

Fetching packages ...
zlib-1.2.8-0.t 100% |###############################| Time: 0:00:00 383.33 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
No psutil available.
To proceed, please conda install psutil#
# To activate this environment, use:
# $ source activate C:\Users\Chris\.julia\v0.6\SymEngine\deps\usr
#
# To deactivate this environment, use:
# $ source deactivate
#

```

**Comment by isuruf** [comment]
Can you try installing psutil?
```Julia
Conda.install("psutil", "C:\Users\Chris\.julia\v0.6\SymEngine\deps\usr")
```

**Comment by ChrisRackauckas** [comment]
```julia
julia> Conda.install("psutil", "C:\Users\Chris\.julia\v0.6\SymEngine\deps\usr")
ERROR: syntax: invalid escape sequence

julia> Conda.install("psutil", "C:\\Users\\Chris\\.julia\\v0.6\\SymEngine\\deps\\usr")
ERROR: UndefVarError: Conda not defined

julia> using Conda

julia> Conda.install("psutil", "C:\\Users\\Chris\\.julia\\v0.6\\SymEngine\\deps\\usr")
ERROR: MethodError: no method matching install(::String, ::String)
Closest candidates are:
  install{T}(::Any, ::Conda.EnvManager{T}) at C:\Users\Chris\.julia\v0.6\Conda\src\bindeps_conda.jl:43
```

**Comment by isuruf** [comment]
Sorry, that should have been
```Julia
Conda.add("psutil", "C:\\Users\\Chris\\.julia\\v0.6\\SymEngine\\deps\\usr")
```

**Comment by ChrisRackauckas** [comment]
👍

**Comment by ChrisRackauckas** [comment]
While that worked on v0.6, on v0.5 I get:

```julia
julia> Conda.add("psutil", "C:\\Users\\Chris\\.julia\\v0.5\\SymEngine\\deps\\usr")
ERROR: ArgumentError: Path to conda environment is not valid.
 in prefix at C:\Users\Chris\.julia\v0.5\Conda\src\Conda.jl:60 [inlined]
 in _install_conda(::String, ::Bool) at C:\Users\Chris\.julia\v0.5\Conda\src\Conda.jl:202
 in runconda at C:\Users\Chris\.julia\v0.5\Conda\src\Conda.jl:130 [inlined]
 in add(::String, ::String) at C:\Users\Chris\.julia\v0.5\Conda\src\Conda.jl:210
```

**Comment by isuruf** [comment]
@ChrisRackauckas, do you still get the `No psutil available.` message?

**Comment by ChrisRackauckas** [comment]
On Conda master? I now get 

```julia
MethodError: no method matching add(::String, ::String)
Closest candidates are:
  add(::AbstractString) at C:\Users\Chris\.julia\v0.6\Conda\src\Conda.jl:145
 in include_string(::String, ::String) at .\loading.jl:478
 in eval(::Module, ::Any) at .\boot.jl:236
 in (::Atom.##61#64)() at C:\Users\Chris\.julia\v0.6\Atom\src\eval.jl:40
 in withpath(::Atom.##61#64, ::Void) at C:\Users\Chris\.julia\v0.6\CodeTools\src\utils.jl:30
 in withpath(::Function, ::Void) at C:\Users\Chris\.julia\v0.6\Atom\src\eval.jl:46
 in macro expansion at C:\Users\Chris\.julia\v0.6\Atom\src\eval.jl:109 [inlined]
 in (::Atom.##60#63)() at .\task.jl:60
```

**Comment by isuruf** [comment]
I thought JuliaLang/METADATA.jl#6861 was merged. Apparently not. Let's wait until it is.

**Pull request merged**
