### PR TITLE
Sl/0.5 compat

### PR DESCRIPTION
**Pull request by spencerlyon2**
Supports Julia 0.5 and 0.4 with no deprecation warnings.

This _should not_ be merged until after Compat.jl version 0.8.5 is tagged (hopefully soon).

This is on top of #25, sorry for not splitting them up. I'm just working on cleaning a few things up to incorporate SymEngine.jl in another package I'm working on.

### CODE REVIEW

**Comment by certik** [comment]
@spencerlyon2 thanks a lot for helping us cleanup the Julia wrappers!

What is your application? I am excited that you find it useful and I would like to learn more about your use case.

**Comment by spencerlyon2** [comment]
@certik no problem. I still have a bit more cleanup to do in my application an in SymEngine.jl, but once I've done it I'm happy to share my applied code with you.

It looks like some tests failed, I'll check that out and fix things up.

**Comment by isuruf** [comment]
Tests pass now that Compat.jl 0.8.5 is there. Can you resolve merge conflicts?

**Comment by spencerlyon2** [comment]
Yes, will do.

I also have a few other changes that clean things up a bit and make the api
easier to use. Do you mind if I include those here, or would prefer a
separate pr?

-- 
Spencer Lyon

**Comment by isuruf** [comment]
It'll be easier to review if this was merged first.

**Comment by spencerlyon2** [comment]
OK I think it is done. Sorry it took a few days.

Once this is merged I'll open another PR with the other changes.

**Comment by certik** [comment]
Thanks @spencerlyon2. Let's see if tests pass.

**Pull request merged**
