### PR TITLE
Add support for lambdify with cse

### PR DESCRIPTION
**Pull request by isuruf**
@Tarlan0001, you can test this branch by compiling symengine master branch as a shared library and then installing it to the SymEngine.jl/deps/symengine-0.3 directory

### CODE REVIEW

**Comment by Tarlan0001** [comment]
Thank you!
Sorry, could you explain how to do it? `Pkg.update()`? Or just copy the changes and paste to my local file?

**Comment by Tarlan0001** [comment]
I copied the changes, it gives now
```
ERROR: LoadError: libsymengine is too old
```

**Comment by isuruf** [comment]
Which OS are you using?

**Comment by Tarlan0001** [comment]
Windows 10

**Comment by isuruf** [comment]
Download https://ci.appveyor.com/api/buildjobs/ghb5857ir7dk36rq/artifacts/symengine_MinGW-w64_x64.zip and copy the `bin/libsymengine.dll` to where `SymEngine.libsymengine` is.

**Pull request merged**
